# Generated by Django 3.1.2 on 2021-06-23 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('idProd', models.AutoField(help_text='Id única del producto', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('region', models.DateField(blank=True, choices=[('I', 'Arica y Parinacota'), ('II', 'Antofagasta'), ('III', 'Atacama y Coquimbo'), ('IV', 'Valparaíso'), ('V', '\tOHiggins'), ('VI', 'Maule'), ('VII', 'Biobío'), ('VIII', 'La Araucanía'), ('IX', 'Los Ríos y Los Lagos'), ('X', 'Los Lagos y Aysén'), ('XI', 'Magallanes'), ('RM', 'Metropolitana de Santiago')], default='RM', help_text='Región')),
                ('comuna', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, choices=[('a', 'Disponible'), ('b', 'Agotado'), ('c', 'Pausada'), ('d', 'No disponible')], default='d', help_text='Disponibilidad', max_length=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
