# Generated by Django 3.1.2 on 2021-06-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='region',
            field=models.CharField(blank=True, choices=[('I', 'Arica y Parinacota'), ('II', 'Antofagasta'), ('III', 'Atacama y Coquimbo'), ('IV', 'Valparaíso'), ('V', '\tOHiggins'), ('VI', 'Maule'), ('VII', 'Biobío'), ('VIII', 'La Araucanía'), ('IX', 'Los Ríos y Los Lagos'), ('X', 'Los Lagos y Aysén'), ('XI', 'Magallanes'), ('RM', 'Metropolitana de Santiago')], default='RM', help_text='Región', max_length=4),
        ),
    ]
