# Generated by Django 3.1.2 on 2021-06-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210622_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha_publicacion',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Disponible'), ('b', 'Agotado'), ('c', 'Pausada'), ('d', 'No disponible')], default='a', help_text='Estado de la publicación', max_length=1),
        ),
    ]
