# Generated by Django 3.1.2 on 2021-06-23 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210622_2235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
