# Generated by Django 3.1.2 on 2021-06-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20210623_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='descripcion',
        ),
    ]
